### ISSUE TITLE
Please create a tag for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [jasmin-lang/coqword#25]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (2.1) **does not work** with Coq `8.18.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit cb8b06aa14ab13b07e04011ae376b3a133cc911d on repository https://github.com/jasmin-lang/coqword - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.18, **preferably before October 31st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before October 31st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.18.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by vbgl** [comment]
I think that the status of this is that this issue is invalid: latest released version (with tag `v2.1`) does work fine with coq 8.18.0.

**Comment by palmskog** [comment]
The package was indeed recently updated to support MathComp 1.18.0 on Coq 8.18.0: https://github.com/coq/opam/pull/2817

**Comment by MSoegtropIMC** [comment]
Out build issues are because we are testing with mathcomp 2.0/2.1. Currently two packages are not compatible, `mathcomp-analysis` and `mathcomp-word`.  Since mathcomp-anaylsis wiill not be 2.0 compatible before the end of the year, we will have two picks in the next release, one with mathcomp 2.1 and without analysis and word, and one with mathcomp 1.18 with all packages.

Is this agreeable?

**Comment by MSoegtropIMC** [comment]
As discussed in Zulip the upcoming release of Coq platform contains two picks, one based on mathcomp 1.18 and one based on mathcomp 2.1. See (https://github.com/math-comp/math-comp/issues/1089).

For coq-mathcomp-word we picked:

MC2.1: **not included**
MC1.18: coq-mathcomp-word.2.1

**If this is what you want, please close this ticket - otherwise please ping us asap.**
